var results=[
	{
		"debate":{
			"first":"RK",
			"second":"AZ",
			"third":"SN",
		},
		"english_elocution":{
			"first":"AZ",
			"second":"NH",
			"third":"RK",
		},
		"hindi_elocution":{
			"first":"RP",
			"second":"PH",
			"third":"MS",
		},
		"bengali_elocution":{
			"first":"RK",
			"second":"AZ",
			"third":"MT",
		},
		"wtgw":{
			"first":"RK",
			"second":"SN",
			"third":"NH",
		},
		"english_dramatics":{
			"first":"NH",
			"second":"AZ",
			"third":"SN",
		},
		"hindi_dramatics":{
			"first":"RP",
			"second":"AZ",
			"third":"PH",
		},
		"bengali_dramatics":{
			"first":"AZ",
			"second":"LLR",
			"third":"RP",
		},
		"postering":{
			"first":"RK",
			"second":"AZ",
			"third":"MS",
		},
		"cartooning":{
			"first":"PH",
			"second":"RK",
			"third":"RP",
		},
		"sketching":{
			"first":"AZ",
			"second":"PH",
			"third":"RP",
		},
		"dumb_charades":{
			"first":"NH",
			"second":"SN",
			"third":"AZ",
		},
		"collaging":{
			"first":"RP",
			"second":"LLR",
			"third":"SN",
		},
		"western_groups":{
			"first":"RK",
			"second":"NH",
			"third":"PH",
		},
		"eastern_groups":{
			"first":"AZ",
			"second":"PH",
			"third":"MT",
		},
		"western_instrumentals":{
			"first":"RK",
			"second":"MS",
			"third":"PH",
		},
		"western_vocals":{
			"first":"SN",
			"second":"LLR",
			"third":"AZ",
		},
		"eastern_instrumentals":{
			"first":"RK",
			"second":"RP",
			"third":"NH",
		},
		"eastern_vocals":{
			"first":"RK",
			"second":"SN",
			"third":"VS",
		},
		"quiz":{
			"first":"RK",
			"second":"RK",
			"third":"NH",
		},
		"clay":{
			"first":"RK",
			"second":"SN,LLR",
			"third":"",
		},
		"choreography":{
			"first":"NH",
			"second":"RK",
			"third":"PH",
		},
	},
	{
		"debate":{
			"first":"AZ",
			"second":"SN",
			"third":"RK",
		},
		"english_elocution":{
			"first":"RK",
			"second":"RP",
			"third":"NH",
		},
		"hindi_elocution":{
			"first":"RP",
			"second":"RK",
			"third":"MS",
		},
		"bengali_elocution":{
			"first":"RK",
			"second":"LLR",
			"third":"NH",
		},
		"wtgw":{
			"first":"PH",
			"second":"SN",
			"third":"",
		},
		"english_dramatics":{
			"first":"SN",
			"second":"AZ",
			"third":"NH",
		},
		"hindi_dramatics":{
			"first":"AZ",
			"second":"RK,SN",
			"third":"",
		},
		"bengali_dramatics":{
			"first":"AZ",
			"second":"NH",
			"third":"JCB",
		},
		"postering":{
			"first":"RP",
			"second":"RK",
			"third":"SN",
		},
		"cartooning":{
			"first":"NH",
			"second":"RP",
			"third":"PH",
		},
		"sketching":{
			"first":"NH",
			"second":"HJB",
			"third":"PH,SN",
		},
		"dumb_charades":{
			"first":"AZ",
			"second":"RK",
			"third":"",
		},
		"collaging":{
			"first":"LLR",
			"second":"RP",
			"third":"NH",
		},
		"western_groups":{
			"first":"RK",
			"second":"AZ",
			"third":"LLR",
		},
		"eastern_groups":{
			"first":"RK",
			"second":"AZ",
			"third":"NH",
		},
		"western_instrumentals":{
			"first":"RK",
			"second":"AZ",
			"third":"RP",
		},
		"western_vocals":{
			"first":"MS",
			"second":"AZ",
			"third":"RK",
		},
		"eastern_instrumentals":{
			"first":"RP",
			"second":"PH",
			"third":"LLR",
		},
		"eastern_vocals":{
			"first":"VSRC",
			"second":"MS",
			"third":"NH",
		},
		"quiz":{
			"first":"AZ",
			"second":"NH",
			"third":"RP",
		},
		"clay":{
			"first":"PH",
			"second":"RK",
			"third":"LLR",
		},
		"choreography":{
			"first":"NH",
			"second":"",
			"third":"",
		},
	},
	{
		"debate":{
			"first":"RP",
			"second":"AZ",
			"third":"NH",
		},
		"english_elocution":{
			"first":"NH",
			"second":"AZ",
			"third":"RP",
		},
		"hindi_elocution":{
			"first":"AZ",
			"second":"MT",
			"third":"RK",
		},
		"bengali_elocution":{
			"first":"RP",
			"second":"SN,PH",
			"third":"AZ",
		},
		"wtgw":{
			"first":"PH",
			"second":"SN",
			"third":"RK",
		},
		"english_dramatics":{
			"first":"RK",
			"second":"RP",
			"third":"LLR",
		},
		"hindi_dramatics":{
			"first":"RK",
			"second":"AZ",
			"third":"PH",
		},
		"bengali_dramatics":{
			"first":"RP",
			"second":"RK",
			"third":"AZ",
		},
		"postering":{
			"first":"RP",
			"second":"SN",
			"third":"PH",
		},
		"cartooning":{
			"first":"RP",
			"second":"NH",
			"third":"MS",
		},
		"sketching":{
			"first":"HJB",
			"second":"AZ",
			"third":"RK",
		},
		"dumb_charades":{
			"first":"RK",
			"second":"PH",
			"third":"RP",
		},
		"collaging":{
			"first":"PH",
			"second":"NH",
			"third":"RP",
		},
		"western_groups":{
			"first":"NH",
			"second":"LLR, RP",
			"third":"",
		},
		"eastern_groups":{
			"first":"LLR",
			"second":"RP",
			"third":"AZ",
		},
		"western_instrumentals":{
			"first":"LLR",
			"second":"NH",
			"third":"AZ",
		},
		"western_vocals":{
			"first":"AZ",
			"second":"NH",
			"third":"SN",
		},
		"eastern_instrumentals":{
			"first":"RP",
			"second":"RK",
			"third":"AZ",
		},
		"eastern_vocals":{
			"first":"NH",
			"second":"AZ",
			"third":"VSRC",
		},
		"quiz":{
			"first":"NH",
			"second":"RP",
			"third":"PH",
		},
		"clay":{
			"first":"PH",
			"second":"AZ",
			"third":"RK",
		},
		"choreography":{
			"first":"AZ",
			"second":"RP",
			"third":"SN",
		},
	}
];

var points={
		"debate":{
			"event_name":"Debate",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"english_elocution":{
			"event_name":"English Elocution",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"hindi_elocution":{
			"event_name":"Hindi Elocution",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"bengali_elocution":{
			"event_name":"Bengali Elocution",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"wtgw":{
			"event_name":"What's the Good Word?",
			"first":"75",
			"second":"45",
			"third":"30",
		},
		"english_dramatics":{
			"event_name":"English Dramatics",
			"first":"100",
			"second":"60",
			"third":"40",
		},
		"hindi_dramatics":{
			"event_name":"Hindi Dramatics",
			"first":"100",
			"second":"60",
			"third":"40",
		},
		"bengali_dramatics":{
			"event_name":"Bengali Dramatics",
			"first":"100",
			"second":"60",
			"third":"40",
		},
		"postering":{
			"event_name":"Postering",
			"first":"60",
			"second":"45",
			"third":"25",
		},
		"cartooning":{
			"event_name":"Cartooning",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"sketching":{
			"event_name":"Sketching",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"dumb_charades":{
			"event_name":"Dumb Charades",
			"first":"75",
			"second":"45",
			"third":"30",
		},
		"collaging":{
			"event_name":"Collaging",
			"first":"75",
			"second":"45",
			"third":"30",
		},
		"western_groups":{
			"event_name":"Western Groups",
			"first":"100",
			"second":"60",
			"third":"40",
		},
		"eastern_groups":{
			"event_name":"Eastern Groups",
			"first":"100",
			"second":"60",
			"third":"40",
		},
		"western_instrumentals":{
			"event_name":"Western Instrumentals",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"western_vocals":{
			"event_name":"Western Vocals",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"eastern_instrumentals":{
			"event_name":"Eastern Instrumentals",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"eastern_vocals":{
			"event_name":"Eastern Vocals",
			"first":"60",
			"second":"35",
			"third":"25",
		},
		"quiz":{
			"event_name":"General Quiz",
			"first":"100",
			"second":"60",
			"third":"40",
		},
		"clay":{
			"event_name":"Thermocol and Clay Modelling",
			"first":"100",
			"second":"60",
			"third":"40",
		},
		"choreography":{
			"event_name":"Choreography",
			"first":"100",
			"second":"60",
			"third":"40",
		},
};

var boss={

		"debate":"AZ",
		"english_elocution":"NH",
		"hindi_elocution":"RP",
		"bengali_elocution":"RK",
		"wtgw":"",
		"english_dramatics":"",
		"hindi_dramatics":"AZ",
		"bengali_dramatics":"AZ",
		"postering":"RP",
		"cartooning":"RP",
		"sketching":"",
		"dumb_charades":"RK",
		"collaging":"RP",
		"western_groups":"RK",
		"eastern_groups":"AZ",
		"western_instrumentals":"RK",
		"western_vocals":"AZ",
		"eastern_instrumentals":"RP",
		"eastern_vocals":"",
		"quiz":"NH",
		"clay":"",
		"choreography":"NH",
};
var hi;

function podium(event){
	for(var i=1;i<4;i++){
		document.getElementsByClassName('event_title')[0].innerHTML=points[event].event_name;
		document.getElementsByClassName('points')[0].innerHTML='Gold : '+points[event].first+' points | Silver : '+points[event].second+' points | Bronze : '+points[event].third+' points';
		document.getElementsByClassName(i+'-pod-1')[0].innerHTML=results[i-1][event].first;
		document.getElementsByClassName(i+'-pod-2')[0].innerHTML=results[i-1][event].second;
		document.getElementsByClassName(i+'-pod-3')[0].innerHTML=results[i-1][event].third;
		document.getElementsByClassName('domi')[0].innerHTML = boss[event];
	}
}
